###auth api
###basic test request
GET https://localhost:5000/auth/users HTTP/1.1

### id request
GET https://localhost:5000/auth/user/1 HTTP/1.1

### post user 
POST https://localhost:5000/auth/user HTTP/1.1
Content-Type: application/json

{
	"username": "zack e fron",
	"password": "testPWD",
	"email": "zackefron@mail.com"
}

### login
POST https://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
	"username": "a",
	"password": "a"
}

### delete user
DELETE https://localhost:5000/auth/user/3 HTTP/1.1




### profile api

### update username
PUT https://localhost:5000/profile/changeUsername HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

{
	"username": "toro fortissimo"
}

### get 2fa qrCode 
GET https://localhost:5000/profile/generate2FA HTTP/1.1
Authorization: Bearer jwt token

###  get all user info protetta inserire JWT valido per testarla
GET https://localhost:5000/profile/allUserInfo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhIiwiaWF0IjoxNzUxMjE2Nzc3LCJleHAiOjE3NTEzMDMxNzd9.KX_oBRmHb6kh2OMduzk2BOZK6IvENvKcLMrusvyF8Jg


### verify 2fa protetta inserire JWT valido per testarla
POST  https://localhost:5000/profile/verify2FA HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0b3JvIGZvcnRpc3NpbW8iLCJpYXQiOjE3NTAxODEzNjksImV4cCI6MTc1MDI2Nzc2OX0.Oxjr8fd-AwjvSJdrFlBLJdBWOw5j3E3Hxo4HqpEWeuw

{
	"token": "588683"
}

### change display name
PUT https://localhost:5000/profile/changeUsername HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

{
	"display_name": "toro fortissimo"
}

### change password
PUT https://localhost:5000/profile/changeUsername HTTP/1.1
Content-Type: application/json
Authorization: Bearer <jwt token>

{
	"newPassword": "nuovaPassword",
	"oldPassword": "cory"
}

# chiamata curl per fare il post dell'avatar
# curl -k -X POST https://localhost:5000/profile/uploadAvatar \
#  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJhIiwiaWF0IjoxNzUwNzY1ODA3LCJleHAiOjE3NTA4NTIyMDd9.NcOnx1Y0O99bLeG7HX0yNpPoiIIsYyLg_uqM9REXrAo" \
# -F "avatar=@/home/jacar/smiling-guy.jpg"