FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Base + Node.js 20 LTS
RUN apt-get update && apt-get install -y \
    curl ca-certificates gnupg git build-essential \
 && rm -rf /var/lib/apt/lists/*docker build

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get update && apt-get install -y nodejs \
 && rm -rf /var/lib/apt/lists/*

# Variabili e workdir
ENV PROJECT_ROOT=/workspace/transcendence
ENV APP_DIR=/workspace/transcendence/app
WORKDIR ${APP_DIR}

# Entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Espone la porta usata in dev
EXPOSE 5000

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "run", "dev"]
